### PR TITLE
this way work on both platforms.

### PR DESCRIPTION
**Pull request by rafatackla**
Closes seahen/maven-s3-wagon#16 

 - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6213298

 - https://stackoverflow.com/questions/1000183/reliable-file-renameto-alternative-on-windows

### CODE REVIEW

**Comment by qiao-rsa** [comment]
I think I am having the same issue on Windows. Can we release a version with this fix?

**Comment by dbolotin** [comment]
We also experience the problem.

**Comment by dbolotin** [comment]
For those who also stuck with this issue, before this pull request will be merged, one can use [the build](https://jitpack.io/#rafatackla/maven-s3-wagon/bugfix~problem_download_artifact_windows-SNAPSHOT) from the JitPack:
```xml
<project>
    ...
    <pluginRepositories>
        <pluginRepository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </pluginRepository>
    </pluginRepositories>
    ...
    <build>
        <extensions>
            <extension>
                <groupId>com.github.rafatackla</groupId>
                <artifactId>maven-s3-wagon</artifactId>
                <version>bugfix~problem_download_artifact_windows-maven-s3-wagon-1.3.1-g11681f8-2</version>
            </extension>
        </extensions>
        ...
    </build>
</project>
```

**Comment by seahen** [comment]
This looks reasonable, that is a better way to do it.

**Pull request merged**
